name: Latest You tube videos.

on:
  schedule:
    #Run everyday at 5 UTC
    - cron: "0 5 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme-with-youtube:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comments-tag-name: "YOUTUBE"
          feed_list: https://www.youtube.com/feeds/videos.xml?channel_id=UCb6e-URYu5CcXpskbb7lgpg
